services:
  php:
    build:
      context: ./ 
      dockerfile: Dockerfile 
    container_name: container_php 
    restart: always 
    volumes:
      - ./src:/var/www/html:cached  
    ports:
      - "80:80" 
    networks:
      - app-network 
    
  db:
    image: postgres
    container_name: container_postgres
    restart: always 
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "5432:5432" 
    environment:
      MYSQL_ROOT_PASSWORD: postgres123 
      MYSQL_DATABASE: aval_acao_crud 
      MYSQL_USER: postdba
      MYSQL_PASSWORD: postgres123
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge