services:
  php:
    build:
      context: ./ 
      dockerfile: Dockerfile 
    container_name: container_php 
    restart: always 
    volumes:
      - ./src:/var/www/html:cached  
    ports:
      - "80:80" 
    networks:
      - app-network 
    
  postgres:
    image: postgres:12
    container_name: container_postgres
    restart: always 
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: postgres123 
      POSTGRES_USER: postgres
      POSTGRES_DB: aval_acao_crud
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge